# Generated by Django 5.0 on 2023-12-21 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_user',
            field=models.JSONField(default=datetime.datetime(2023, 12, 21, 6, 40, 52, 249271, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
