# Generated by Django 5.0 on 2023-12-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_task_subtasks_task_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
