# Generated by Django 5.0 on 2023-12-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_remove_task_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
