# Generated by Django 5.0 on 2023-12-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
