# Generated by Django 5.0 on 2023-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idBox',
            field=models.JSONField(default=2023),
            preserve_default=False,
        ),
    ]
