# Generated by Django 5.0 on 2023-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_task_idbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='idBox',
            field=models.CharField(max_length=10),
        ),
    ]
