# Generated by Django 5.0 on 2023-12-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_remove_contact_created_at_remove_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
    ]
