# Generated by Django 5.0 on 2023-12-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_rename_created_contact_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
