# Generated by Django 5.0 on 2023-12-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.CharField(max_length=150),
        ),
    ]
